<?php
/**
 * ListConfirmedTransactionsByAddressRIBSZVShieldedSpend
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace CryptoAPIs\Model;

use \ArrayAccess;
use \CryptoAPIs\ObjectSerializer;

/**
 * ListConfirmedTransactionsByAddressRIBSZVShieldedSpend Class Doc Comment
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ListConfirmedTransactionsByAddressRIBSZVShieldedSpend implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListConfirmedTransactionsByAddressRIBSZ_vShieldedSpend';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'anchor' => 'string',
        'cv' => 'string',
        'nullifier' => 'string',
        'proof' => 'string',
        'rk' => 'string',
        'spend_auth_sig' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'anchor' => null,
        'cv' => null,
        'nullifier' => null,
        'proof' => null,
        'rk' => null,
        'spend_auth_sig' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'anchor' => 'anchor',
        'cv' => 'cv',
        'nullifier' => 'nullifier',
        'proof' => 'proof',
        'rk' => 'rk',
        'spend_auth_sig' => 'spendAuthSig'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'anchor' => 'setAnchor',
        'cv' => 'setCv',
        'nullifier' => 'setNullifier',
        'proof' => 'setProof',
        'rk' => 'setRk',
        'spend_auth_sig' => 'setSpendAuthSig'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'anchor' => 'getAnchor',
        'cv' => 'getCv',
        'nullifier' => 'getNullifier',
        'proof' => 'getProof',
        'rk' => 'getRk',
        'spend_auth_sig' => 'getSpendAuthSig'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['anchor'] = $data['anchor'] ?? null;
        $this->container['cv'] = $data['cv'] ?? null;
        $this->container['nullifier'] = $data['nullifier'] ?? null;
        $this->container['proof'] = $data['proof'] ?? null;
        $this->container['rk'] = $data['rk'] ?? null;
        $this->container['spend_auth_sig'] = $data['spend_auth_sig'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['anchor'] === null) {
            $invalidProperties[] = "'anchor' can't be null";
        }
        if ($this->container['cv'] === null) {
            $invalidProperties[] = "'cv' can't be null";
        }
        if ($this->container['nullifier'] === null) {
            $invalidProperties[] = "'nullifier' can't be null";
        }
        if ($this->container['proof'] === null) {
            $invalidProperties[] = "'proof' can't be null";
        }
        if ($this->container['rk'] === null) {
            $invalidProperties[] = "'rk' can't be null";
        }
        if ($this->container['spend_auth_sig'] === null) {
            $invalidProperties[] = "'spend_auth_sig' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets anchor
     *
     * @return string
     */
    public function getAnchor()
    {
        return $this->container['anchor'];
    }

    /**
     * Sets anchor
     *
     * @param string $anchor Defines a Merkle tree root of a note commitment tree which uniquely identifies a note commitment tree state given the assumed security properties of the Merkle tree’s  hash function.
     *
     * @return self
     */
    public function setAnchor($anchor)
    {
        $this->container['anchor'] = $anchor;

        return $this;
    }

    /**
     * Gets cv
     *
     * @return string
     */
    public function getCv()
    {
        return $this->container['cv'];
    }

    /**
     * Sets cv
     *
     * @param string $cv Defines a value commitment to the value of the input note.
     *
     * @return self
     */
    public function setCv($cv)
    {
        $this->container['cv'] = $cv;

        return $this;
    }

    /**
     * Gets nullifier
     *
     * @return string
     */
    public function getNullifier()
    {
        return $this->container['nullifier'];
    }

    /**
     * Sets nullifier
     *
     * @param string $nullifier Represents a sequence of nullifiers of the input notes.
     *
     * @return self
     */
    public function setNullifier($nullifier)
    {
        $this->container['nullifier'] = $nullifier;

        return $this;
    }

    /**
     * Gets proof
     *
     * @return string
     */
    public function getProof()
    {
        return $this->container['proof'];
    }

    /**
     * Sets proof
     *
     * @param string $proof Represents the proof.
     *
     * @return self
     */
    public function setProof($proof)
    {
        $this->container['proof'] = $proof;

        return $this;
    }

    /**
     * Gets rk
     *
     * @return string
     */
    public function getRk()
    {
        return $this->container['rk'];
    }

    /**
     * Sets rk
     *
     * @param string $rk Represents the randomized validating key for spendAuthSig.
     *
     * @return self
     */
    public function setRk($rk)
    {
        $this->container['rk'] = $rk;

        return $this;
    }

    /**
     * Gets spend_auth_sig
     *
     * @return string
     */
    public function getSpendAuthSig()
    {
        return $this->container['spend_auth_sig'];
    }

    /**
     * Sets spend_auth_sig
     *
     * @param string $spend_auth_sig Used to prove knowledge of the spending key authorizing spending of an input note.
     *
     * @return self
     */
    public function setSpendAuthSig($spend_auth_sig)
    {
        $this->container['spend_auth_sig'] = $spend_auth_sig;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


