<?php
/**
 * GetExchangeRateByAssetsIDsRITest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CryptoAPIs\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetExchangeRateByAssetsIDsRITest Class Doc Comment
 *
 * @category    Class
 * @description GetExchangeRateByAssetsIDsRI
 * @package     CryptoAPIs
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetExchangeRateByAssetsIDsRITest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetExchangeRateByAssetsIDsRI"
     */
    public function testGetExchangeRateByAssetsIDsRI()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "calculation_timestamp"
     */
    public function testPropertyCalculationTimestamp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_asset_id"
     */
    public function testPropertyFromAssetId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_asset_symbol"
     */
    public function testPropertyFromAssetSymbol()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_asset_id"
     */
    public function testPropertyToAssetId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_asset_symbol"
     */
    public function testPropertyToAssetSymbol()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
