<?php
/**
 * HDWalletsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace CryptoAPIs\Test\Api;

use \CryptoAPIs\Configuration;
use \CryptoAPIs\ApiException;
use \CryptoAPIs\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * HDWalletsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HDWalletsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getHDWalletXPubYPubZPubDetails
     *
     * Get HD Wallet (xPub, yPub, zPub) Details.
     *
     */
    public function testGetHDWalletXPubYPubZPubDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listHDWalletXPubYPubZPubTransactions
     *
     * List HD Wallet (xPub, yPub, zPub) Transactions.
     *
     */
    public function testListHDWalletXPubYPubZPubTransactions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncHDWalletXPubYPubZPub
     *
     * Sync HD Wallet (xPub, yPub, zPub).
     *
     */
    public function testSyncHDWalletXPubYPubZPub()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
