<?php
/**
 * UnifiedEndpointsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace CryptoAPIs\Test\Api;

use \CryptoAPIs\Configuration;
use \CryptoAPIs\ApiException;
use \CryptoAPIs\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UnifiedEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UnifiedEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAddressDetails
     *
     * Get Address Details.
     *
     */
    public function testGetAddressDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBlockDetailsByBlockHash
     *
     * Get Block Details By Block Hash.
     *
     */
    public function testGetBlockDetailsByBlockHash()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBlockDetailsByBlockHeight
     *
     * Get Block Details By Block Height.
     *
     */
    public function testGetBlockDetailsByBlockHeight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFeeRecommendations
     *
     * Get Fee Recommendations.
     *
     */
    public function testGetFeeRecommendations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLatestMinedBlock
     *
     * Get Latest Mined Block.
     *
     */
    public function testGetLatestMinedBlock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionDetailsByTransactionID
     *
     * Get Transaction Details By Transaction ID.
     *
     */
    public function testGetTransactionDetailsByTransactionID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTransactionsByAddress
     *
     * List Transactions By Address.
     *
     */
    public function testListTransactionsByAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTransactionsByBlockHash
     *
     * List Transactions by Block Hash.
     *
     */
    public function testListTransactionsByBlockHash()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTransactionsByBlockHeight
     *
     * List Transactions by Block Height.
     *
     */
    public function testListTransactionsByBlockHeight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
