<?php
/**
 * ZilliqaApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace CryptoAPIs\Test\Api;

use \CryptoAPIs\Configuration;
use \CryptoAPIs\ApiException;
use \CryptoAPIs\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ZilliqaApiTest Class Doc Comment
 *
 * @category Class
 * @package  CryptoAPIs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZilliqaApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getLatestMinedZilliqaBlock
     *
     * Get Latest Mined Zilliqa Block.
     *
     */
    public function testGetLatestMinedZilliqaBlock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getZilliqaAddressDetails
     *
     * Get Zilliqa Address Details.
     *
     */
    public function testGetZilliqaAddressDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getZilliqaBlockDetailsByBlockHash
     *
     * Get Zilliqa Block Details By Block Hash.
     *
     */
    public function testGetZilliqaBlockDetailsByBlockHash()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getZilliqaBlockDetailsByBlockHeight
     *
     * Get Zilliqa Block Details By Block Height.
     *
     */
    public function testGetZilliqaBlockDetailsByBlockHeight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getZilliqaTransactionDetailsByTransactionID
     *
     * Get Zilliqa Transaction Details by Transaction ID.
     *
     */
    public function testGetZilliqaTransactionDetailsByTransactionID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZilliqaTransactionsByAddress
     *
     * List Zilliqa Transactions by Address.
     *
     */
    public function testListZilliqaTransactionsByAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZilliqaTransactionsByBlockHash
     *
     * List Zilliqa Transactions By Block Hash.
     *
     */
    public function testListZilliqaTransactionsByBlockHash()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listZilliqaTransactionsByBlockHeight
     *
     * List Zilliqa Transactions By Block Height.
     *
     */
    public function testListZilliqaTransactionsByBlockHeight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
